version: "3.7"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: snippetbox
      POSTGRES_PASSWORD: snippetbox
      PG_DATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - snippetbox
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: aitumik@protonmail.com
      PGADMIN_DEFAULT_PASSWORD : snippetbox!@x1$$aitumik
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - snippetbox
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
    ports:
      - "9200:9200"
      - "9300:9300"
networks:
  snippetbox:
    driver: bridge
volumes:
  postgres:
  pgadmin:
