version: "3.7"

services:

# Application
  snippetbox:
    container_name: snippetbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./:/snippetbox

# Database
  postgres:
    env_file: .env
    image: "postgres"
    hostname: "postgres"
    ports:
        - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    env_file: .env


# Adminer
  adminer:
    container_name: adminer
    image: dockette/adminer
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - postgres
 
# Volumes
volumes:
  esdata:
    driver: local
  pgdata:
    driver: local

    

