version: "3.7"

services:

# Application
  snippetbox:
    container_name: snippetbox
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    links:
      - "database:db"
    env_file: .env

# Database
  database:
    image: postgres
    hostname: db
    volumes:
      - pgdata:/var/lib/postgresql/data/snippetbox
    ports:
      - "5432:5432"
    env_file: .env

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    env_file: .env

# Adminer
  adminer:
    container_name: adminer
    image: dockette/adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
 
# Volumes
volumes:
  esdata:
    driver: local
  pgdata:
    driver: local

    

