version: "3.7"

networks:
  snippetbox:
services:
  snippetbox:
    container_name: snippetbox
    build: .
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - snippetbox:/usr/src/app/
    networks:
      - snippetbox
  db:
    container_name: snippetbox_database
    image: postgres
    environment:
      POSTGRES_USER: snippetbox
      POSTGRES_PASSWORD: snippetbox
      POSTGRES_DB: snippetbox
      PG_DATA: "/data/postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - snippetbox
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: aitumik@protonmail.com
      PGADMIN_DEFAULT_PASSWORD : snippetbox!@x1$$aitumik
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - db
    links:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - snippetbox
    restart: always
volumes:
  postgres_data:
  pgadmin:
  snippetbox: