version: "3.7"

services:
# Application
  snippetbox:
    container_name: snippetbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./:/snippetbox
# Database
  postgres:
    env_file: .env
    image: "postgres"
    hostname: "postgres"
    ports:
        - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
# Adminer
  admner:
    container_name: admner
    image: dockette/adminer
    restart: always
    ports:
      - "8085:80"
    depends_on:
      - postgres
# Volumes
volumes:
  pgdata:
    driver: local